### ISSUE TITLE
Support androidx.lifecycle.ViewModel

### ISSUE THREAD

**Issue by ersin-ertan** [InsertKoinIO/getting-started-koin-android#1]
Support for: androidx.lifecycle.ViewModel

Creating my `val appModule = module { viewModel` doesn't work because `MyViewModel:ViewModel()` isn't a subtype of `android.arch.lifecycle.ViewModel` see `ContextExt`

**Comment by neiljaywarner** [comment]
bump - is this still accurate? I thought there were androidx dependencies?

**Comment by ersin-ertan** [comment]
Thanks for the update @neiljaywarner, not at the time of posting
